name: Validar HTML en cada Push

on:
  push:
    branches:
      - main
      - "feature/*"
      - "dev-*"
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Install Linkinator
        run: npm install -g linkinator

      - name: Lint HTML files
        run: htmlhint "**/*.html"

      - name: Check broken links
        run: linkinator . --skip "mailto:*"
